<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sixthumbs.Core\Sixthumbs.Core.csproj" />
    <PackageReference Include="ppy.SDL3-CS" Version="2026.722.0" />
  </ItemGroup>
</Project>
